[project]
name = "news-bias-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "datasets>=4.5.0",
    "playwright>=1.58.0",
    "polars>=1.38.1",
]
